name: PyPI

on:
  release:
    types: [published]

jobs:
  publish-pypi:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install twine jinja2

    - name: Build Python package
      run: |
        python setup_init.py ${{ github.event.release.tag_name }}
        python setup.py sdist bdist_wheel

    - name: Twine check
      run: |
        twine check dist/*

    - name: Upload to PyPI
      run: |
        twine upload dist/* -u ${{ secrets.PYPI_LOGIN }} -p ${{ secrets.PYPI_PASSWORD }}

  publish-dockerhub:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile -t dnstap-receiver

    - name: Tag image
      run: |
        docker tag dnstap-receiver dmachard/dnstap-receiver:${{ github.event.release.tag_name }}
        docker tag dnstap-receiver dmachard/dnstap-receiver:latest

    - name: Upload to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/dnstap-receiver:latest
        docker push dmachard/dnstap-receiver:${{ github.event.release.tag_name }}