name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Run Python tests 
      run: |
        sudo python3 -m pip install -r requirements.txt
        sudo python3 -m pip install --upgrade dnspython protobuf
        sudo python3 -m unittest tests.test_external_config -v
        sudo python3 -m unittest tests.test_api_server -v
