name: Testing Module

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Run Python tests 
      run: |
        sudo python3 -m pip install dnstap_pb pyyaml aiohttp geoip2 tlds cachetools fstrm
        sudo python3 -m pip install --upgrade dnspython protobuf
        sudo python3 -m unittest tests.test_external_config -v
        sudo python3 -m unittest tests.test_api_server -v
