name: Testing E2E - dnsdist

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DNS_SERVER_IP: "127.0.0.1"
  DNS_SERVER_PORT: "5553"

jobs:
  dnsdist:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        dnsdist: [ '16', '17' ]
        python: [ '3.10' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: add pdns user
      run: |
        sudo addgroup --system --gid 953 pdns
        sudo adduser --system --disabled-password --no-create-home -uid 953 --gid 953 pdns
        sudo mkdir /tmp/dnsdist
        sudo chown -R pdns:pdns /tmp/dnsdist/

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/dnsdist.conf:/etc/dnsdist/conf.d/dnsdist.conf:ro -v /tmp/dnsdist/:/tmp/dnsdist/ powerdns/dnsdist-${{ matrix.dnsdist }}
        until (dig -p 5553 www.github.com @127.0.0.1 | grep NOERROR); do sleep 5.0; done
        
    - name: Run Python tests 
      run: |
        sudo python -m pip install -r requirements.txt
        sudo python -m pip install --upgrade dnspython protobuf
        sudo -E python -m unittest tests.test_receiver_tcpsocket -v
        sudo -u pdns -s python -m pip install -r requirements.txt
        sudo -u pdns -s python -m pip install --upgrade dnspython protobuf
        sudo -E python -m unittest tests.test_receiver_unixsocket -v
