name: Testing dnsdist

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DNS_SERVER_IP: "127.0.0.1"
  DNS_SERVER_PORT: "5553"

jobs:
  dnsdist16:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d -p 5553:53/udp -p 5353:53/tcp --network="host" --name=dnsdist --volume=$PWD/tests/dnsdist.conf:/etc/dnsdist/conf.d/dnsdist.conf:ro powerdns/dnsdist-16
        sudo netstat -anp |grep 5553
    - name: Run Python tests 
      run: |
        sudo python3 -m pip install dnstap_pb pyyaml aiohttp geoip2 tlds cachetools fstrm
        sudo python3 -m pip install --upgrade dnspython protobuf
        sudo -E python3 -m unittest tests.test_receiver_tcpsocket -v